### ISSUE TITLE
Missing textures – Thermal Foundation & Mystical World

### ISSUE THREAD

**Issue by Dimentive** [Aang23/UndergroundBiomesConstructs#208] opened 2020-01-03 06:52 UTC
**Textures that are missing:**
• Oil Shale from [Thermal Foundation](https://www.curseforge.com/minecraft/mc-mods/thermal-foundation)
• Amethyst Ore, Copper Ore, and Silver Ore from [Mystical World](https://www.curseforge.com/minecraft/mc-mods/mystical-world)

![Screenshot showcasing the missing-texture ores from Underground Biomes next to the original blocks from the original mods.](https://i.imgur.com/0GwQIrJ.png)

The missing textures for Mystical World ores have been reported before: #151, #152, #157.
However, the missing textures for Thermal Foundation’s oil shale haven’t been reported before, and two of those issues are closed even though this problem hasn’t been fixed yet.

#### Versions
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2847 (latest for 1.12.2)
* **Underground Biomes:** 1.3.7 (latest for 1.12.2)
* **Thermal Foundation:** 2.6.3.27 (latest for 1.12.2)
* **Mystical World:** 1.5.0

**Comment by sealchan1** [comment] 2020-01-21 01:07
I also see Oil Sand having the missing texture issue.

Same Minecraft and mod versions except Mystical World 1.7.0

**Comment by Enderized** [comment] 2020-01-30 22:42
About the Oil, reason could probably be a missing oil.png.mcmeta file like the Destabilized Redstone has...

Added a custom resourcepack \assets\undergroundbiomes\textures\blocks\overlays\thermalfoundation\oil.png.mcmeta and it works

couldnt find a fix for the mysticalworld ore tho :/

Versions

- Underground Biomes: 1.3.7
- Thermal Foundation: 2.6.3.27
- Mystical World: 1.7.1

**Comment by Excederus** [comment] 2020-02-10 05:39
The json file for Mystical World (in config/undergroundbiomes/ores) still contains a wrong path to the texture. "undergroundbiomes:" repeats itself. Just remove one and it's fixed.

**Comment by Excederus** [comment] 2020-02-10 07:26
I found a kind of hacky fix for this.

1. Open the mod.jar with 7-zip
2. Go to the overlay textures ("assets/undergroundbiomes/textures/blocks/overlays")
3. Create a new folder and call it whatever you want (I called it "mystworld")
4. Go into the original "mysticalWorld" folder and copy the .png files
5. Go into your created folder and paste them there
6. Close 7-zip
7. Go to the ores configs ("config/undergroundbiomes/ores")
8. Open the mysticalworld.json
9. Replace the texture path with your path (for example "undergroundbiomes:blocks/overlays/mystworld/copper" - replacing "mystworld" with the name you gave the folder and "copper" with the material that you are editing in the file)

This method can also be used for adding not supported mods to underground biomes (for example crystal ore from Electroblob's Wizardry)

**Comment by AechtRob** [comment] 2020-02-16 09:58
For the MysticalWorld one, my texture-loss in 1.12.2 was being caused by a wrongly-constructed filepath in the generated json in the config folder. That file is created the first time the mod is launched, and afterwards can be edited as a regular config file, without editing the mod itself. Open the installation config folder "undergroundbiomes" and browse to the mysticalworld.json file. Inside that you will see that these filepaths have a duplicated string in them, so change them as follows:

"overlay": "undergroundbiomes:undergroundbiomes:blocks/overlays/mysticalWorld/amethyst",
TO:
"overlay": "undergroundbiomes:blocks/overlays/mysticalWorld/amethyst",

And do that for all three. Save, the json, close and re-launch the installation.

**Comment by Enderized** [comment] 2020-02-16 11:31
personally i wanted to avoid the editing of the .jar- but as long as it works i'm fine by that

**Comment by AechtRob** [comment] 2020-02-16 13:23
Yep I agree too - this needs a proper mod update release as editing the jar won't be fixed in modpacks/Twitch launchers. The alternative is to create a texture pack to cover the gaps as mentioned above. I have put one together here if anyone wants to use it temporarily, which adds the missing meta file for Thermal Foundation and reapplies the standard Mystical overlays to whatever UBC block textures are in use (in theory this works on top of any other 3rd party UBC texturepack too - if that doesn't already have its own working Mystical integration): 

https://www.curseforge.com/minecraft/texture-packs/underground-biomes-missing-texture-fix

I'm happy to update that with every/all missing textures for the time being if you use the comment thread in it to request. Until UBC gets fixed :)

**Comment by Aang23** [comment] 2020-02-18 12:44
Instead of editing the .jar a resource loader could work... The issue is known and easy to fix just didn't get to it

**Closed** 2020-04-09 13:23 UTC
Labels: 1.12.2, bug, confirmed

**Comment by Dimentive** [comment] 2020-08-04 05:23
Since this was closed, has this issue been fixed in the latest versions?
