### ISSUE TITLE
[1.12.2] Crash ticking world [Unknown Source]

### ISSUE THREAD

**Issue by NickelHub** [Aang23/UndergroundBiomesConstructs#3] opened 2018-09-26 23:28 UTC
I had a unknown crash, whilst I was travelling through the world. I post it to all mods that seems to be in the crash, maybe someone could find the bug. I had this crash several times. Same as https://github.com/josephcsible/Oreberries/issues/17 and https://github.com/sp614x/optifine/issues/1837

Could be related to https://github.com/sp614x/optifine/issues/1488 or https://github.com/iChun/IssueTracker-Mods/issues/61 

See crash log for detailed mod information.

[crash-2018-09-27_01.21.51-client.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/2421885/crash-2018-09-27_01.21.51-client.txt)
[crash-2018-09-27_01.20.49-server.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/2421886/crash-2018-09-27_01.20.49-server.txt)

**Comment by josephcsible** [comment] 2018-09-26 23:45
This looks like it may be related to NuclearCraft as well as this mod. I don't think Oreberries or OptiFine are related.

**Comment by josephcsible** [comment] 2018-09-27 01:06
turbodiesel4598/NuclearCraft#366 will fix this, but you could also work around this on your side.

**Comment by Aang23** [comment] 2018-09-27 09:38
Thanls for fixing this in NC... This actually was the only mod causing this bug but I may do a workaround to prevent further issues.

**Comment by NickelHub** [comment] 2018-10-01 14:13
Did you find a workaround for that? There isn't any new build of NuclearCraft available so can't move through my worlds now.

**Comment by Aang23** [comment] 2018-10-01 15:31
I've not looked at that because I tough the fixed NC version was out... I may add some workaround in 1.3.0.

**Comment by NickelHub** [comment] 2018-10-01 15:35
It is merged. But there is no version out and I failed to build myself.

**Comment by Aang23** [comment] 2018-10-01 19:06
That fixes this issue, but I hope this will not cause any other one, at least this should not. Considering that now this is only active for NC ores...

**Comment by Aang23** [comment] 2018-10-01 19:11
I'm closing it, but that will get reopened if necessary. Do not hesitate to post here.

**Closed by Aang23** 2018-10-01 19:11 UTC
Labels: Fixed, Other Mod, enhancement

**Comment by josephcsible** [comment] 2018-10-01 19:18
It looks like that won't in fact fix the crash. The problem is the function you're calling ignores the state parameter entirely, so just changing what you pass to it can't possibly fix it,

**Comment by Aang23** [comment] 2018-10-01 19:29
I know but the state that was returned with the previous method isn't actually viable, as it is not actually block-specific but gotten from the mod config file, and not intended to be used for anything else than the metadata, this is the same thing that actually caused https://github.com/Aang23/UndergroundBiomesConstructs/issues/6 
As a short term workaround, returning the DefaultState value allows avoiding crashes while I'm working on something a bit better, like actually using the original ore's blockstate instead.
